# Generated by Django 6.0.1 on 2026-02-02 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favourites', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favoriteslist',
            name='scanner_model',
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='favorites_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='usersettings.favoriteslist'),
        ),
        migrations.AlterField(
            model_name='channelgroup',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='usersettings.scannerprofile'),
        ),
    ]
