# Generated by Django 6.0.1 on 2026-02-02 04:17

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agency_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgroup_id', models.BigIntegerField(blank=True, null=True)),
                ('name_tag', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('range_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50)),
                ('emergency_alert', models.CharField(blank=True, default='Off', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='FavoritesList',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('location_control', models.CharField(default='Off', max_length=10)),
                ('monitor', models.CharField(default='Off', max_length=10)),
                ('quick_key', models.CharField(blank=True, default='Off', max_length=10)),
                ('number_tag', models.CharField(blank=True, default='Off', max_length=10)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('scanner_model', models.CharField(choices=[('BCDx36HP', 'BCDx36HP'), ('BCD536HP', 'BCD536HP'), ('BCD436HP', 'BCD436HP'), ('SDS100', 'SDS100'), ('SDS150', 'SDS150'), ('SDS200', 'SDS200')], default='BCDx36HP', max_length=50)),
                ('order', models.IntegerField(default=0)),
                ('startup_keys', models.JSONField(default=list)),
                ('s_qkeys', models.JSONField(default=list)),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'number_tag'],
            },
        ),
        migrations.CreateModel(
            name='ScannerProfile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=50)),
                ('scanner_model', models.CharField(choices=[('BCDx36HP', 'BCDx36HP'), ('BCD536HP', 'BCD536HP'), ('BCD436HP', 'BCD436HP'), ('SDS100', 'SDS100'), ('SDS150', 'SDS150'), ('SDS200', 'SDS200')], default='BCDx36HP', max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='profiles/')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerRawFile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ScannerFileRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('record_type', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('spec_field_order', models.JSONField(default=list)),
                ('spec_field_map', models.JSONField(default=dict)),
                ('trailing_empty_fields', models.IntegerField(default=0)),
                ('line_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['file_path', 'line_number'],
                'indexes': [models.Index(fields=['file_path', 'line_number'], name='usersetting_file_pa_1aa07d_idx'), models.Index(fields=['record_type'], name='usersetting_record__56720a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('frequency', models.BigIntegerField()),
                ('modulation', models.CharField(choices=[('FM', 'FM'), ('NFM', 'NFM'), ('AM', 'AM'), ('AUTO', 'AUTO')], max_length=20)),
                ('audio_option', models.CharField(blank=True, max_length=50)),
                ('delay', models.IntegerField(default=15)),
                ('attenuator', models.CharField(blank=True, default='Off', max_length=10)),
                ('number_tag', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('alert_tone', models.CharField(blank=True, default='Off', max_length=10)),
                ('alert_light', models.CharField(blank=True, default='Off', max_length=10)),
                ('volume_offset', models.CharField(blank=True, default='Off', max_length=10)),
                ('p_ch', models.CharField(blank=True, default='Off', max_length=10)),
                ('reserved', models.CharField(blank=True, default='Off', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('channel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='usersettings.channelgroup')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='frequencies_alt', to='usersettings.scannerprofile')),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
        migrations.AddField(
            model_name='channelgroup',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='usersettings.scannerprofile'),
        ),
        migrations.CreateModel(
            name='ScannerRawLine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='usersettings.scannerrawfile')),
            ],
            options={
                'ordering': ['raw_file', 'line_number'],
                'indexes': [models.Index(fields=['raw_file', 'line_number'], name='usersetting_raw_fil_7ef966_idx')],
            },
        ),
    ]
