# Generated by Django 6.0.1 on 2026-02-01 21:58

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('agency_id', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FavoritesList',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('filename', models.CharField(max_length=255)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('scanner_model', models.CharField(choices=[('BCDx36HP', 'BCDx36HP'), ('BCD536HP', 'BCD536HP'), ('BCD436HP', 'BCD436HP'), ('SDS100', 'SDS100'), ('SDS150', 'SDS150'), ('SDS200', 'SDS200')], default='BCDx36HP', max_length=50)),
                ('enabled', models.BooleanField(default=False)),
                ('disabled_on_power', models.BooleanField(default=True)),
                ('quick_key', models.CharField(blank=True, max_length=10)),
                ('list_number', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('flags', models.TextField(blank=True)),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'list_number'],
            },
        ),
        migrations.CreateModel(
            name='ScannerProfile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=50)),
                ('scanner_model', models.CharField(choices=[('BCDx36HP', 'BCDx36HP'), ('BCD536HP', 'BCD536HP'), ('BCD436HP', 'BCD436HP'), ('SDS100', 'SDS100'), ('SDS150', 'SDS150'), ('SDS200', 'SDS200')], default='BCDx36HP', max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=20)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_file', models.FileField(blank=True, null=True, upload_to='profiles/')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ScannerRawFile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='ScannerFileRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('record_type', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('spec_field_order', models.JSONField(default=list)),
                ('spec_field_map', models.JSONField(default=dict)),
                ('trailing_empty_fields', models.IntegerField(default=0)),
                ('line_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['file_path', 'line_number'],
                'indexes': [models.Index(fields=['file_path', 'line_number'], name='usersetting_file_pa_1aa07d_idx'), models.Index(fields=['record_type'], name='usersetting_record__56720a_idx')],
            },
        ),
        migrations.CreateModel(
            name='Frequency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('frequency', models.BigIntegerField()),
                ('modulation', models.CharField(choices=[('FM', 'FM'), ('AM', 'AM'), ('AUTO', 'AUTO')], max_length=10)),
                ('nac', models.CharField(blank=True, max_length=10)),
                ('enabled', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='usersettings.scannerprofile')),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
        migrations.CreateModel(
            name='ChannelGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('frequencies', models.ManyToManyField(blank=True, related_name='groups', to='usersettings.frequency')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='usersettings.scannerprofile')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScannerRawLine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='usersettings.scannerrawfile')),
            ],
            options={
                'ordering': ['raw_file', 'line_number'],
                'indexes': [models.Index(fields=['raw_file', 'line_number'], name='usersetting_raw_fil_7ef966_idx')],
            },
        ),
    ]
