# Generated by Django 6.0.1 on 2026-02-01 21:58

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='HPDBImportJob',
            fields=[
                ('job_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Upload Complete'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('uploaded_files', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('processing_stage', models.CharField(blank=True, max_length=50)),
                ('current_file', models.CharField(blank=True, max_length=255)),
                ('processed_files', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HPDBRawFile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['country_id'],
                'indexes': [models.Index(fields=['country_id'], name='hpdb_countr_country_b1fee9_idx')],
            },
        ),
        migrations.CreateModel(
            name='HPDBAgency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('Conventional', 'Conventional'), ('Trunk', 'Trunk')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('quick_key', models.CharField(blank=True, default='Off', max_length=10)),
                ('emergency_alert', models.CharField(blank=True, default='Off', max_length=10)),
                ('number_tag', models.IntegerField(blank=True, null=True)),
                ('hold_time', models.CharField(blank=True, default='Off', max_length=10)),
                ('priority_id_scan', models.CharField(blank=True, default='Off', max_length=10)),
                ('agc_analog', models.IntegerField(blank=True, default=400)),
                ('agc_digital', models.CharField(blank=True, default='Manual', max_length=20)),
                ('number_tag_index', models.IntegerField(blank=True, default=0)),
                ('trunk_id_search', models.CharField(blank=True, default='', max_length=20)),
                ('trunk_end_code', models.CharField(blank=True, default='', max_length=20)),
                ('trunk_fleet_map', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_unit_id', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_emergency_alert_light', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_agc', models.CharField(blank=True, default='Analog', max_length=20)),
                ('trunk_status_bit', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_reserved1', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_reserved2', models.CharField(blank=True, default='Off', max_length=10)),
                ('trunk_nxdn_format', models.CharField(blank=True, default='', max_length=20)),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counties', models.ManyToManyField(blank=True, related_name='hpdb_agencies', to='hpdb.county')),
            ],
            options={
                'verbose_name_plural': 'HPDB Agencies',
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='HPDBChannelGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgroup_id', models.BigIntegerField()),
                ('name_tag', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('range_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50)),
                ('emergency_alert', models.CharField(blank=True, default='Off', max_length=10)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='hpdb.hpdbagency')),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='HPDBDQKsStatus',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quick_key_status', models.JSONField(default=list)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quick_key_status', to='hpdb.hpdbagency')),
            ],
            options={
                'verbose_name': 'HPDB Quick Key Status',
                'verbose_name_plural': 'HPDB Quick Key Statuses',
            },
        ),
        migrations.CreateModel(
            name='HPDBFileRecord',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('record_type', models.CharField(max_length=100)),
                ('fields', models.JSONField(default=list)),
                ('spec_field_order', models.JSONField(default=list)),
                ('spec_field_map', models.JSONField(default=dict)),
                ('trailing_empty_fields', models.IntegerField(default=0)),
                ('line_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['file_path', 'line_number'],
                'indexes': [models.Index(fields=['file_path', 'line_number'], name='hpdb_hpdbfi_file_pa_db0aab_idx'), models.Index(fields=['record_type'], name='hpdb_hpdbfi_record__57f86f_idx')],
            },
        ),
        migrations.CreateModel(
            name='HPDBFrequency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfreq_id', models.BigIntegerField()),
                ('name_tag', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.BigIntegerField()),
                ('modulation', models.CharField(max_length=20)),
                ('audio_option', models.CharField(blank=True, max_length=50)),
                ('delay', models.IntegerField(default=15)),
                ('attenuator', models.CharField(blank=True, default='Off', max_length=10)),
                ('number_tag', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('alert_tone', models.CharField(blank=True, default='Off', max_length=10)),
                ('alert_light', models.CharField(blank=True, default='Off', max_length=10)),
                ('volume_offset', models.CharField(blank=True, default='Off', max_length=10)),
                ('p_ch', models.CharField(blank=True, default='Off', max_length=10)),
                ('reserved', models.CharField(blank=True, default='Off', max_length=10)),
                ('raw_data', models.TextField(blank=True)),
                ('cgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='hpdb.hpdbchannelgroup')),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
        migrations.CreateModel(
            name='HPDBRawLine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hpdb.hpdbrawfile')),
            ],
            options={
                'ordering': ['raw_file', 'line_number'],
            },
        ),
        migrations.CreateModel(
            name='HPDBSite',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('range_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('modulation', models.CharField(blank=True, default='AUTO', max_length=20)),
                ('bandwidth', models.CharField(blank=True, default='Standard', max_length=20)),
                ('band_type', models.CharField(blank=True, default='Wide', max_length=20)),
                ('location_type', models.CharField(blank=True, default='Circle', max_length=20)),
                ('emergency_alert', models.CharField(blank=True, default='Off', max_length=10)),
                ('agc_analog', models.IntegerField(blank=True, default=400)),
                ('agc_digital', models.CharField(blank=True, default='Manual', max_length=20)),
                ('number_tag', models.IntegerField(blank=True, null=True)),
                ('reserved', models.CharField(blank=True, default='Off', max_length=10)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='hpdb.hpdbagency')),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='HPDBTFreq',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.BigIntegerField()),
                ('lcn', models.IntegerField(default=0)),
                ('mode', models.CharField(blank=True, default='Srch', max_length=20)),
                ('raw_data', models.TextField(blank=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='hpdb.hpdbsite')),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
        migrations.CreateModel(
            name='HPDBTGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('range_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('location_type', models.CharField(blank=True, default='Circle', max_length=20)),
                ('emergency_alert', models.CharField(blank=True, default='Off', max_length=10)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='talk_groups', to='hpdb.hpdbagency')),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.CreateModel(
            name='HPDBTGID',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_tag', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('tgid', models.IntegerField()),
                ('audio_type', models.CharField(blank=True, default='ALL', max_length=20)),
                ('delay', models.IntegerField(default=208)),
                ('number_tag', models.IntegerField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, default=0)),
                ('alert_tone', models.CharField(blank=True, default='Off', max_length=10)),
                ('alert_light', models.CharField(blank=True, default='Off', max_length=10)),
                ('reserved1', models.CharField(blank=True, default='Off', max_length=10)),
                ('volume_offset', models.CharField(blank=True, default='Off', max_length=10)),
                ('reserved2', models.CharField(blank=True, default='Off', max_length=10)),
                ('reserved3', models.CharField(blank=True, default='Off', max_length=10)),
                ('match_type', models.CharField(blank=True, default='Any', max_length=20)),
                ('raw_data', models.TextField(blank=True)),
                ('tgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tgids', to='hpdb.hpdbtgroup')),
            ],
            options={
                'ordering': ['tgid'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(unique=True)),
                ('name_tag', models.CharField(max_length=255)),
                ('short_name', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hpdb.country')),
            ],
            options={
                'ordering': ['name_tag'],
            },
        ),
        migrations.AddField(
            model_name='hpdbagency',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='hpdb_agencies', to='hpdb.state'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='hpdb.state'),
        ),
        migrations.CreateModel(
            name='HPDBBandPlan',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(choices=[('P25', 'P25'), ('Motorola', 'Motorola')], max_length=20)),
                ('band_plan_data', models.JSONField(default=list)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='band_plans', to='hpdb.hpdbagency')),
            ],
            options={
                'verbose_name': 'HPDB Band Plan',
                'indexes': [models.Index(fields=['agency'], name='hpdb_hpdbba_agency__181613_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='hpdbchannelgroup',
            index=models.Index(fields=['cgroup_id'], name='hpdb_hpdbch_cgroup__19df8a_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbchannelgroup',
            index=models.Index(fields=['agency'], name='hpdb_hpdbch_agency__14fd20_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbdqksstatus',
            index=models.Index(fields=['agency'], name='hpdb_hpdbdq_agency__6925bd_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbfrequency',
            index=models.Index(fields=['cfreq_id'], name='hpdb_hpdbfr_cfreq_i_611fc9_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbfrequency',
            index=models.Index(fields=['cgroup'], name='hpdb_hpdbfr_cgroup__cfd5ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbrawline',
            index=models.Index(fields=['raw_file', 'line_number'], name='hpdb_hpdbra_raw_fil_9d1304_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbsite',
            index=models.Index(fields=['agency'], name='hpdb_hpdbsi_agency__5fc735_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbtfreq',
            index=models.Index(fields=['site'], name='hpdb_hpdbtf_site_id_e05d43_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbtgroup',
            index=models.Index(fields=['agency'], name='hpdb_hpdbtg_agency__7c90ef_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbtgid',
            index=models.Index(fields=['tgroup'], name='hpdb_hpdbtg_tgroup__474431_idx'),
        ),
        migrations.AddIndex(
            model_name='hpdbtgid',
            index=models.Index(fields=['tgid'], name='hpdb_hpdbtg_tgid_3dbcce_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['state_id'], name='hpdb_state_state_i_0f739a_idx'),
        ),
        migrations.AddIndex(
            model_name='state',
            index=models.Index(fields=['country'], name='hpdb_state_country_90d0e1_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['county_id'], name='hpdb_county_county__89880f_idx'),
        ),
        migrations.AddIndex(
            model_name='county',
            index=models.Index(fields=['state'], name='hpdb_county_state_i_aa6b10_idx'),
        ),
    ]
