# Generated by Django 6.0.1 on 2026-01-31 15:23

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Counties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HPDBAgency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('system_type', models.CharField(choices=[('Conventional', 'Conventional'), ('Trunk', 'Trunk')], max_length=20)),
                ('enabled', models.BooleanField(default=False)),
                ('raw_data', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counties', models.ManyToManyField(blank=True, related_name='hpdb_agencies', to='hpdb.county')),
            ],
            options={
                'verbose_name_plural': 'HPDB Agencies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HPDBChannelGroup',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgroup_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('range_miles', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('location_type', models.CharField(blank=True, max_length=50)),
                ('raw_data', models.TextField(blank=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='hpdb.hpdbagency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HPDBFrequency',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfreq_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('frequency', models.BigIntegerField()),
                ('modulation', models.CharField(max_length=20)),
                ('tone', models.CharField(blank=True, max_length=50)),
                ('delay', models.IntegerField(default=15)),
                ('raw_data', models.TextField(blank=True)),
                ('cgroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frequencies', to='hpdb.hpdbchannelgroup')),
            ],
            options={
                'ordering': ['frequency'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='hpdb.country')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='hpdbagency',
            name='states',
            field=models.ManyToManyField(blank=True, related_name='hpdb_agencies', to='hpdb.state'),
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counties', to='hpdb.state'),
        ),
    ]
