# Generated by Django 6.0.1 on 2026-01-31 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hpdbfrequency',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hpdbfrequency',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
