# Generated by Django 6.0.1 on 2026-02-02 04:19

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hpdbimportjob',
            name='status',
            field=models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Upload Complete'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='uploading', max_length=20),
        ),
        migrations.CreateModel(
            name='HPDBRectangle',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_1', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_1', models.DecimalField(decimal_places=6, max_digits=10)),
                ('latitude_2', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude_2', models.DecimalField(decimal_places=6, max_digits=10)),
                ('channel_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rectangles', to='hpdb.hpdbchannelgroup')),
            ],
            options={
                'verbose_name_plural': 'HPDB Rectangles',
                'indexes': [models.Index(fields=['channel_group'], name='hpdb_hpdbre_channel_1bd967_idx')],
            },
        ),
    ]
