# Generated by Django 6.0.1 on 2026-01-31 16:50

import django.db.models.deletion
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hpdb', '0002_hpdbfrequency_description_alter_hpdbfrequency_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HPDBImportJob',
            fields=[
                ('job_id', models.CharField(max_length=36, primary_key=True, serialize=False, unique=True)),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('uploaded', 'Upload Complete'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploading', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('uploaded_files', models.IntegerField(default=0)),
                ('total_bytes', models.BigIntegerField(default=0)),
                ('uploaded_bytes', models.BigIntegerField(default=0)),
                ('processing_stage', models.CharField(blank=True, max_length=50)),
                ('current_file', models.CharField(blank=True, max_length=255)),
                ('processed_files', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('result_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HPDBRawFile',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=50)),
                ('file_size', models.IntegerField()),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='HPDBRawLine',
            fields=[
                ('id', django_mongodb_backend.fields.ObjectIdAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.IntegerField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('raw_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='hpdb.hpdbrawfile')),
            ],
            options={
                'ordering': ['raw_file', 'line_number'],
                'indexes': [models.Index(fields=['raw_file', 'line_number'], name='hpdb_hpdbra_raw_fil_9d1304_idx')],
            },
        ),
    ]
